version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - superai-net

  frontend:
    container_name: frontend
    working_dir: /app
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"  
    networks:
      - superai-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - frontend
    networks:
      - superai-net

networks:
  superai-net:
    driver: bridge
